RadarsDocLibrary/Models/DocumentUpload.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadarsDocLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentupload
    {
        public string radarserialno { get; set; }
        public string eventdate { get; set; }
        public string documentname { get; set; }
        public string documentuploaddate { get; set; }
        public string filesystempath { get; set; }
        public string updatedby { get; set; }
    }
}

RadarsDocLibrary/Controllers/ApplicationController.cs
/* 
* Need to parameterize everything in the jobscheduler and email job and add parameters to web.config
 * * * * to do...
 * add cancel to slin???
 * add cancel to CDRL Date??
 * 
 * add "Back to ?" to documents screen (and all associated coding)
 * 
 * * 
 *        ***BUG*** Timezone issues. 
 *      ***BUG*** The user database for cdrl is pointing to the one for radarsfleettracker. Need to configure something in IIS
 * *         ***TODO*** Add "Back" buttons to documents
 *
 * *    There is a timezone issue. When adding OptionPeriods or ContractActionPersonnel early 
 *        morning, the dates chosen are showing up in the jqgrid as the day before. 
 * *                          
 *                 

 * *  
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.IO;
using System.Reflection;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using RadarsDocLibrary.Models;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using RadarsDocLibrary;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Text;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using System.Security.Principal;
using System.Threading;
using System.Collections;

namespace RadarsDocLibrary.Controllers
{
    [Authorize]
//    public class ApplicationController : Controller
    public class ApplicationController : AccountController
    {
        Utilities goUtilities = new Utilities();

        public ActionResult AppError()
        {
            return View();
        }

        public ActionResult AuthError()
        {
            return View();
        }

        public ActionResult DocLibEntry()
        {
            return View();
        }

        public ActionResult DocumentUploadEntry()
        {
// this function gets called via ajax from the ContractActionEntry form
            string ltAction = "nothing";
            string ltContractActionPersonnelID = "0";

            if(Request.QueryString["whichaction"] != null)
                ltAction = Request.QueryString["whichaction"];
            
            switch (ltAction.ToLower())
            {
                case "newrecord":
                        DocumentUploads2 loDoc = new DocumentUploads2();
                        loDoc.DateTimeAdded = DateTime.Now.ToString();
                        loDoc.OwningEntityID = 0;
                        loDoc.OwningEntityTable = "DocumentCat";
//                    ContractActionPersonnel loCAP = new ContractActionPersonnel();
//                    System.Web.HttpContext.Current.Session["ContractActionPersonnelID"] = null;
//                    loCAP.ContractActionID = Int32.Parse(System.Web.HttpContext.Current.Session["CurrentContractActionID"].ToString());
                    return PartialView(loDoc);
                    break;
//                case "update":
//                        DocumentUploads2 loDoc = new DocumentUploads2();
//                        loDoc.DateTimeAdded = DateTime.Now.ToString();
//                        loDoc.OwningEntityID = 0;
//                        loDoc.OwningEntityTable = "DocumentCat";
//                    return PartialView(loDoc);
//                    break;
            }

            return PartialView();
        }

        [HttpPost]
//        [ValidateAntiForgeryToken]
        public JsonResult DocumentUploadAjax(String DocumentID, String DateTimeAdded, String OwningEntityTable, String OwningEntityID, String DocumentName)
        {
            var file = Request.Files[0];
            int liDocID = 0;
//            var fileName = Path.GetFileName( file.FileName );
//            var path = Path.Combine( Server.MapPath( "~/Junk/" ) , fileName );
//            file.SaveAs( path );    


            try
            {
                if (file != null && file.ContentLength > 0)
                {
//   Future enhancement ... should put this in a transaction that we can roll back if one part fails. 
                    RadarsFleetManagerEntities radarsDB = new RadarsFleetManagerEntities();
                    DocumentUploads2 loDocUpload = new DocumentUploads2();
                    loDocUpload.DocumentID = Int32.Parse(DocumentID);
                    loDocUpload.DocumentName = DocumentName;
                    loDocUpload.OwningEntityID = Int32.Parse(OwningEntityID);
                    loDocUpload.OwningEntityTable = OwningEntityTable;
                    loDocUpload.DateTimeAdded = DateTimeAdded;
                    loDocUpload.DocumentPath = "temp";
                    radarsDB.DocumentUploads2.Add(loDocUpload);
                    radarsDB.SaveChanges();
                    if(!goUtilities.AddAuditRecord(User, loDocUpload, "Add"))
                    {
                            Logger.Error("Error Adding " + loDocUpload.GetType().Name + " Audit record for : " + User.Identity.Name);
                            throw new InvalidDataException();
                    }

                    string ltFileName = Path.GetFileName(file.FileName);
                    string ltRadarsUploadLoc = goUtilities.getSettingsVal("uploadedfilelocation");

                    ltFileName = "DocID"+"_"+ loDocUpload.DocumentID + "_" + loDocUpload.DocumentName + "_" + ltFileName;
                    liDocID = loDocUpload.DocumentID;                    
            
                    if(System.Web.HttpContext.Current.Session["CurrentDocUploadList"] != null)
                        if(System.Web.HttpContext.Current.Session["CurrentDocUploadList"].ToString().Contains(','))
                            System.Web.HttpContext.Current.Session["CurrentDocUploadList"] += ","+ ltFileName;
                        else
                            System.Web.HttpContext.Current.Session["CurrentDocUploadList"] += ltFileName;
                    else
                        System.Web.HttpContext.Current.Session["CurrentDocUploadList"] += ltFileName;

                                

//                                string ltOutputPath = Path.Combine("c:\\Files\\RadarsUploads\\", ltFileName);
                    string ltOutputPath = Path.Combine(@ltRadarsUploadLoc, ltFileName);
                    // Prepend path with document id to avoid duplicates
                    loDocUpload.DocumentPath = ltOutputPath;
                    radarsDB.DocumentUploads2.Attach(loDocUpload);
                    radarsDB.Entry(loDocUpload).State = System.Data.Entity.EntityState.Modified;
                    radarsDB.SaveChanges();
                    if(!goUtilities.AddAuditRecord(User, loDocUpload, "Update"))
                    {
                            Logger.Error("Error Adding " + loDocUpload.GetType().Name + " Audit record for : " + User.Identity.Name);
                            throw new InvalidDataException();
                    }


                    file.SaveAs(ltOutputPath);                    
                    if(!goUtilities.AddAuditRecord(User, loDocUpload, "DocUpload"))
                    {
                            Logger.Error("Error Adding " + loDocUpload.GetType().Name + " Audit record for : " + User.Identity.Name);
                            throw new InvalidDataException();
                    }
                    System.Web.HttpContext.Current.Session["DisplayMessage"] = "Successfully uploaded " + DocumentName + " into database.";
                }
                else
                {
                    System.Web.HttpContext.Current.Session["DisplayMessage"] = "Error with document upload. Content length = 0";
                    Logger.Error("Error with document upload. Document is null or content length is 0");
                }
            }

            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    System.Web.HttpContext.Current.Session["DisplayMessage"] = "Entity of type : " + eve.Entry.Entity.GetType().Name + " in state : " + eve.Entry.State + " has the following validation errors: ";
                    Logger.Error("Entity of type : " + eve.Entry.Entity.GetType().Name + " in state : " + eve.Entry.State + " has the following validation errors: ");
                    foreach (var ve in eve.ValidationErrors)
                    {
                        System.Web.HttpContext.Current.Session["DisplayMessage"] += "- Property: " + ve.PropertyName + " , Error: " + ve.ErrorMessage;
                        Logger.Error("- Property: " + ve.PropertyName + " , Error: " + ve.ErrorMessage);
                    }
                }
                //                    throw;
            }
            catch (DbUpdateException ue)
            {
                Logger.Error("DBUpdate Exception : ");
                Logger.Error(ue);
                System.Web.HttpContext.Current.Session["DisplayMessage"] = "DBUpdate Exception : " + ue.InnerException.InnerException.Message;
            }

            catch (Exception ex)
            {
                Logger.Error("File Error : " + ex);
                throw;
            }

            var jsonData = new
            {
                success = true,
                message = "Successfully uploaded document : " + DocumentName,
                docName = DocumentName,
                docID = liDocID
            };


        return Json(jsonData);
        }





        [HttpPost]
//        [ValidateAntiForgeryToken]
        public JsonResult SaveJSTree(String JsonString)
        {
// browser

RadarsDocLibrary/Views/Application/AddOptionPeriodPartial.cshtml
@model RadarsCDRLTracker.Models.PeriodOfPerformance
@{
    ViewBag.Title = "Option Period Entry";
    Utilities lutilRadars = new Utilities();
    string ltContextPath = Request.Url.GetLeftPart(UriPartial.Authority) + Request.ApplicationPath;
    int liContractActionID = (int)System.Web.HttpContext.Current.Session["CurrentContractActionID"];
    if(Model.PeriodOfPerformanceID == 0)
    {
        Model.PeriodOfPerformanceStartDate = DateTime.Today;
        Model.PeriodOfPerformanceEndDate = DateTime.Today;
    }

}

<div id="PMRadarsAddData">
    <h2>@ViewBag.Title.</h2>
    <div class="StatusMessage">@System.Web.HttpContext.Current.Session["DisplayMessage"]</div>

    @using (Html.BeginForm("AddOptionPeriod", "Application", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <!--    <h4>PM Radars Data Entry.</h4> -->
        <hr />
        @Html.ValidationSummary()
        <div class="form-group">

            <table class="twocolumndataentry" width="100%">
                <tr>
                    <td class="datalabel" valign="top">
                        @Html.HiddenFor(m => m.PeriodOfPerformanceID)
                        @Html.LabelFor(m => m.ContractActionID, new {@class = "col-md-2 control-label" })
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.ContractActionID, new {@class = "form-control", @readonly = "readonly"})
                        </div>
                    </td>
                    <td class="datalabel" valign="top">
                        @Html.LabelFor(m => m.PeriodOfPerformanceTypeID, new {@class = "col-md-2 control-label"})
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            @{
                                    using(var ctxPMDB = new RadarsCDRLTracker.Models.RadarsContractTrackerEntities()) {
                                        var linqPOPTypes = ctxPMDB.PeriodOfPerformanceTypes;
                                        @Html.DropDownListFor(m => m.PeriodOfPerformanceTypeID, new SelectList(linqPOPTypes, "PeriodOfPerformanceTypeID", "PeriodOfPerformanceTypeDesc"), new {@class = "form-control"})
                                    }
                            }
                        </div>
                    </td>
                </tr>
                <tr>
                    <td class="datalabel" valign="top">
                        @Html.LabelFor(m => m.PeriodOfPerformanceStartDate,new { @class = "col-md-2 control-label" })
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.PeriodOfPerformanceStartDate,"{0:MM/dd/yyyy}",new { @class = "form-control" })
                        </div>
                    </td>

                    <td class="datalabel" valign="top">
                        @Html.LabelFor(m => m.PeriodOfPerformanceEndDate, new { @class = "col-md-2 control-label" })
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.PeriodOfPerformanceEndDate, "{0:MM/dd/yyyy}", new { @class = "form-control" })
                        </div>
                    </td>

                </tr>

                <tr>
                    <td class="tdForFormButtons" colspan="6" valign="top">
                        <div> &nbsp;</div>
                            <input type="submit" name="whichaction" id="savedata" class="btn btn-default" value="Save Data" />
                            <input type="submit" name="whichaction" id="cancel" class="btn btn-default" value="Cancel" />
                    </td>
                </tr>

            </table>

        </div>
    }

RadarsDocLibrary/Views/Application/AppError.cshtml
@{
    string ltErrorMsg = "";    
    ViewBag.Title = "AppError";
    if (Request.QueryString["errmessage"] != null)
    {
        ltErrorMsg = Request.QueryString["errmessage"];
    }
}

<h2>AppError</h2>

The system has encountered an error. Please contact your support (listed on contact us page). Provide a description of what application function you were trying to perform, what time the error occurred and your user id.  
<br />
<br />

@ltErrorMsg

RadarsDocLibrary/Views/Application/AuditLogList.cshtml
@model RadarsDocLibrary.Models.AuditTable

@{
    ViewBag.Title = "Audit Log";
    var llstRecords = Model;
    Utilities lutilRadars = new Utilities();
    string ltContextPath = Request.Url.GetLeftPart(UriPartial.Authority) + Request.ApplicationPath;

}

<script type="text/javascript">
    jQuery(document).ready(function () {
            @{
                <text>
                var changedtable = @Html.Raw(lutilRadars.getAuditChangedTable());
                var changedby = @Html.Raw(lutilRadars.getAuditChangedBy());
                var updatetype = @Html.Raw(lutilRadars.getAuditUpdateType());
                </text>
            }

            getUniqueNames = function (columnName) {

                switch (columnName)
                {
                    case "ChangedTable":
                        return changedtable;
                        break;
                    case "ChangedBy":
                        return changedby;
                        break;
                    case "UpdateType":
                        return updatetype;
                        break;
                }
            },
            buildSearchSelect = function (uniqueNames) {
                var values = ":All";
                $.each(uniqueNames, function () {
                    values += ";" + this + ":" + this;
                });
                return values;
            },
            setSearchSelect = function (columnName) {
                //            alert(getUniqueNames.call(this, columnName));
                this.jqGrid("setColProp", columnName, {
                    stype: "select",
                    searchoptions: {
                        value: buildSearchSelect(getUniqueNames.call(this, columnName)),
                        sopt: ["eq"]
                    }
                });
            };


        myGrid = jQuery("#ReferenceGrid");
        myGrid.jqGrid({
            url: '@ltContextPath/Application/AuditLogGridData/',
            datatype: 'json',
            gridview: true,
            rownumbers: true,
            //            loadonce: true,
            ignoreCase: true,
            scroll: 0,
            mtype: 'GET',
            colNames: ['ChangedTable', 'SchemaVersionID', 'ChangedDateTime', 'ChangedBy', 'SerializedChange', 'UpdateType'],
            colModel: [
                        { name: 'ChangedTable', sortable: true, Index: 'ChangedTable', width: 95 },
                        { name: 'SchemaVersionID', sortable: true, Index: 'SchemaVersionID', width: 95 },
                        { name: 'ChangedDateTime',  sortable: true, Index: 'ChangedDateTime', width: 125 },
                        { name: 'ChangedBy', sortable: true, Index: 'ChangedBy', width: 95 },
                        { name: 'SerializedChange', sortable: true, Index: 'SerializedChange', width: 700, cellattr: function (rowId, tv, rawObject, cm, rdata) { return 'style="white-space: normal;"' } },
                        { name: 'UpdateType', sortable: true, Index: 'UpdateType', width: 95 }],
            pager: '#pager',
            rowNum: 10,
            rowList: [5, 10, 20, 50],
            sortname: 'ChangedDateTime',
            sortorder: "asc",
//            autowidth: true,
            viewrecords: true,
//            ondblClickRow: function(rowId) {
//                var rowData = jQuery(this).getRowData(rowId);
//                var theid = rowData['ActionTypeID'];
//                console.log("@ltContextPath/Application/ActionTypeEntry?whichaction=update&key=" + theid);
//                document.location.href = "@ltContextPath/Application/ActionTypeEntry?whichaction=update&key=" + theid;
//            }
        });
        myGrid.jqGrid('navGrid', '#pager', { edit: false, add: false, del: false, search: false, refresh: false }, {}, {}, {},
    { multipleSearch: true, overlay: false });

        setSearchSelect.call(myGrid, "ChangedTable");
        setSearchSelect.call(myGrid, "ChangedBy");
        setSearchSelect.call(myGrid, "UpdateType");

        myGrid.jqGrid("setColProp", "Name", {
            searchoptions: {
                sopt: ["cn"],
                dataInit: function (elem) {
                    $(elem).autocomplete({
                        source: getUniqueNames.call($(this), "Name"),
                        delay: 0,
                        minLength: 0,
                        select: function (event, ui) {
                            var myGrid, grid;
                            $(elem).val(ui.item.value);
                            if (typeof elem.id === "string" && elem.id.substr(0, 3) === "gs_") {
                                myGrid = $(elem).closest("div.ui-jqgrid-hdiv").next("div.ui-jqgrid-bdiv").find("table.ui-jqgrid-btable").first();
                                if (myGrid.length > 0) {
                                    grid = myGrid[0];
                                    if ($.isFunction(grid.triggerToolbar)) {
                                        grid.triggerToolbar();
                                    }
                                }
                            } else {
                                // to refresh the filter
                                $(elem).trigger("change");
                            }
                        }
                    });
                }
            }
        });

        myGrid.jqGrid('filterToolbar', {
            stringResult: true, searchOnEnter: true, defaultSearch: "cn", beforeSearch: function () {
                // alert("verifying the data");
                var postData = myGrid.jqGrid('getGridParam', 'postData');
                // we use `stringResult: true` so decoding of the search parameters are a little complex
                var searchData = jQuery.parseJSON(postData.filters);
                for (var iRule = 0; iRule < searchData.rules.length; iRule++) {
                    if (searchData.rules[iRule].field === "Name") {
                        var valueToSearch = searchData.rules[iRule].data;
                        if (valueToSearch.length != 5) {
                            alert("The search string MUST de 5 charachters length!");
                            return true;    // error
                        }
                    }
                }
                return false;
            }
        });
        myGrid.jqGrid('navButtonAdd', '#pager',
        {
            caption: "Filter",
            title: "Toggle Searching Toolbar",
            buttonicon: 'ui-icon-pin-s',
            onClickButton: function () {
                myGrid[0].toggleToolbar();
                setSearchSelect.call(myGrid, "ChangedBy");
            }
        }
        );

        myGrid[0].toggleToolbar();

    });

//    function DeleteConfirm(key) {
//        if (confirm("Are you sure you wish to delete " + key))
//        {
//            window.location.href = "@ltContextPath/Application/ActionTypeEntry?whichaction=delete&key=" + key + "&returnurl=/ActionTypeList";
//        }

//    }
//    function EditRecord(key) {
//        window.location.href = "@ltContextPath/Application/ActionTypeEntry?whichaction=update&key=" + key + "&returnurl=/ActionTypeList";
//    }
//        
</script>

    <div class="StatusMessage">@System.Web.HttpContext.Current.Session["DisplayMessage"]</div>

@using(Html.BeginForm("AuditLogEntry","Application",FormMethod.Post,new { @class = "form-horizontal",role = "form" }))
{
@Html.AntiForgeryToken()
@Html.ValidationSummary()

    <div id="ReferenceTableDescDIV">
        <h2>@ViewBag.Title</h2>
        <table id="ReferenceGrid"><tr><td></td></tr></table>
        <div id="pager" align="left"></div>
    </div>
}

    <div class="StatusMessage">@System.Web.HttpContext.Current.Session["DisplayMessage"]</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@{
    System.Web.HttpContext.Current.Session["DisplayMessage"] = " ";
}

RadarsDocLibrary/Views/Application/AuthError.cshtml
@{
    ViewBag.Title = "AppError";
}

<h2>Authorization Error</h2>

The application could not authorize your Windows credentials. Please contact your application administrator.  

RadarsDocLibrary/Views/Application/DocLibOrganizeEntry.cshtml
@model RadarsDocLibrary.Models.DocumentUpload
           
@{
    ViewBag.Title = "Document Upload";
    String ltOwningEntityTable = System.Web.HttpContext.Current.Session["CurrentOwningEntityTable"].ToString();
    String ltOwningEntityID = System.Web.HttpContext.Current.Session["CurrentOwningEntityID"].ToString();
}

<div id="PMRadarsAddData">
    <h2>@ViewBag.Title.</h2>
    <div class="StatusMessage">@System.Web.HttpContext.Current.Session["DisplayMessage"]</div>
    @using (Html.BeginForm("DocumentUpload", "Application", null, FormMethod.Post, new {enctype = "multipart/form-data"})) 
    {
        @Html.AntiForgeryToken()
        <!--    <h4>PM Radars Data Entry.</h4> -->
        <hr />
        @Html.ValidationSummary()
        <div class="form-group">
            <table class="twocolumndataentry" width="100%">
                <tr>
                    <td class="datalabel" valign="top">
                        @Html.HiddenFor(m => m.DocumentID)
                        @Html.HiddenFor(m => m.DateTimeAdded)
                        @Html.HiddenFor(m => m.OwningEntityTable)
                        @Html.HiddenFor(m => m.OwningEntityID)
                        @Html.LabelFor(m => m.DocumentName, new { @class = "col-md-2 control-label" })
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            @Html.TextBoxFor(Model => Model.DocumentName,new { @class = "form-control" })
                        </div>
                    </td>
                    <td class="datalabel" valign="top">
                        "Locate Document"
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            <input type="file" name="UploadDocument" />                            
                        </div>
                    </td>
                </tr>

                <tr>
                    <td class="tdForFormButtons" colspan="4" valign="top">
                        <div> &nbsp;</div>
                            <input type="submit" name="whichaction" id="savedata" class="btn btn-default" value="Save Data" />
                            <input type="submit" name="whichaction" id="cancel" class="btn btn-default" value="Cancel" />
                    </td>
                </tr>
            </table>
        </div>
    }

   @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    @{
        System.Web.HttpContext.Current.Session["DisplayMessage"] = " ";
    }
</div>

RadarsDocLibrary/Views/Application/DocumentUpload.cshtml
@model RadarsDocLibrary.Models.DocumentUpload
           
@{
    ViewBag.Title = "Document Upload";
    String ltOwningEntityTable = System.Web.HttpContext.Current.Session["CurrentOwningEntityTable"].ToString();
    String ltOwningEntityID = System.Web.HttpContext.Current.Session["CurrentOwningEntityID"].ToString();
}

<div id="PMRadarsAddData">
    <h2>@ViewBag.Title.</h2>
    <div class="StatusMessage">@System.Web.HttpContext.Current.Session["DisplayMessage"]</div>
    @using (Html.BeginForm("DocumentUpload", "Application", null, FormMethod.Post, new {enctype = "multipart/form-data"})) 
    {
        @Html.AntiForgeryToken()
        <!--    <h4>PM Radars Data Entry.</h4> -->
        <hr />
        @Html.ValidationSummary()
        <div class="form-group">
            <table class="twocolumndataentry" width="100%">
                <tr>
                    <td class="datalabel" valign="top">
                        @Html.HiddenFor(m => m.DocumentID)
                        @Html.HiddenFor(m => m.DateTimeAdded)
                        @Html.HiddenFor(m => m.OwningEntityTable)
                        @Html.HiddenFor(m => m.OwningEntityID)
                        @Html.LabelFor(m => m.DocumentName, new { @class = "col-md-2 control-label" })
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            @Html.TextBoxFor(Model => Model.DocumentName,new { @class = "form-control" })
                        </div>
                    </td>
                    <td class="datalabel" valign="top">
                        "Locate Document"
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            <input type="file" name="UploadDocument" />                            
                        </div>
                    </td>
                </tr>

                <tr>
                    <td class="tdForFormButtons" colspan="4" valign="top">
                        <div> &nbsp;</div>
                            <input type="submit" name="whichaction" id="savedata" class="btn btn-default" value="Save Data" />
                            <input type="submit" name="whichaction" id="cancel" class="btn btn-default" value="Cancel" />
                    </td>
                </tr>
            </table>
        </div>
    }

   @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    @{
        System.Web.HttpContext.Current.Session["DisplayMessage"] = " ";
    }
</div>

RadarsDocLibrary/Views/Application/DocumentUploadEntry.cshtml
@model RadarsDocLibrary.Models.DocumentUploads2
           
@{
    ViewBag.Title = "Document Upload";
    String ltOwningEntityTable = System.Web.HttpContext.Current.Session["CurrentOwningEntityTable"].ToString();
    String ltOwningEntityID = System.Web.HttpContext.Current.Session["CurrentOwningEntityID"].ToString();
    Utilities lutilRadars = new Utilities();
    string ltContextPath = Request.Url.GetLeftPart(UriPartial.Authority) + Request.ApplicationPath;
}

<script>
    $('#DocUploadForm').submit(function (e) {
        e.preventDefault();
        console.log("DocUploadForm preventdefault on submit executed");
    })
</script>
<div id="PMRadarsAddData2">
    <h2>@ViewBag.Title.</h2>
    <div class="StatusMessage">@System.Web.HttpContext.Current.Session["DisplayMessage"]</div>
    @using(Html.BeginForm("DocumentUploadEntry","Application",null,FormMethod.Post,new { enctype = "multipart/form-data",id = "DocUploadForm" })) 
    {
        @Html.AntiForgeryToken()
        <!--    <h4>PM Radars Data Entry.</h4> -->
        <hr />
        @Html.ValidationSummary()
        <div class="form-group">
            <table class="twocolumndataentry" width="100%">
                <tr>
                    <td class="datalabel" valign="top">
                        @Html.HiddenFor(m => m.DocumentID, new {id = "DocumentID"} )
                        @Html.HiddenFor(m => m.DateTimeAdded, new {id = "DateTimeAdded"})
                        @Html.HiddenFor(m => m.OwningEntityTable, new {id = "OwningEntityTable"})
                        @Html.HiddenFor(m => m.OwningEntityID, new {id = "OwningEntityID"})
                        @Html.LabelFor(m => m.DocumentName, new { @class = "col-md-2 control-label" })
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            @Html.TextBoxFor(Model => Model.DocumentName,new { @class = "form-control", id = "DocumentName" })
                        </div>
                    </td>
                    <td class="datalabel" valign="top">
                        "Locate Document"
                    </td>
                    <td class="datafield" valign="top">
                        <div class="col-md-10">
                            <input type="file" name="UploadDocument" id="UploadDocument" />                            
                        </div>
                    </td>
                </tr>

                <tr>
                    <td class="tdForFormButtons" colspan="4" valign="top">
                        <div> &nbsp;</div>
                            <input type="submit" name="whichaction" id="UploadTheFile" class="btn btn-default" value="Upload File" />
                            <input type="submit" name="whichaction" id="cancelFileUpload" class="btn btn-default" value="Cancel" />
                    </td>
                </tr>
            </table>
        </div>
    }

   @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    @{
        System.Web.HttpContext.Current.Session["DisplayMessage"] = " ";
    }
</div>